language: php
php:
  - '7.0'
services:
  - 'mysql'  
before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
env:
  -APP_KEY=base64:bRd8e3miL+UDbol1o0LagBgYDCS/vTdex3I2+x5IcY4=