language: php
php:
  - '7.0'
services:
  - 'mysql'  
before_script:
  - composer self-update
  - composer install --no-interaction
  - mysql -u root --password="" -e "CREATE DATABASE ci_testing"
  - cp .env.travis .env
  - php artisan migrate
  - php artisan db:seed --class=productSeeder
