language: php
php:
  - '7.0'
services:
  - 'mysql'  
before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed --class=productSeeder
before_install:
  - mysql -e 'create database ci_testing;'
env:
  -APP_KEY=base64:bRd8e3miL+UDbol1o0LagBgYDCS/vTdex3I2+x5IcY4=
  -DB_DATABASE=ci-testing
  -APP_ENV=testing
  -DB_USERNAME=root
  -DB_PASSWORD=